harvestor:
  early_stopped: false
  early_stopping_epoch: 0
  monitor_name: mse
  monitor_vals: []
  training_losses: []
  val_mse: []
  val_rmse: []
misc_info:
  input_x_shape:
  - 100
  - 3
  input_y_shape:
  - 100
  model_config:
    device: cuda
    hidden_layers:
    - 10
    - 10
    n_input: 3
    n_output: 1
  model_init: vanilla_predNet
  save_path_and_name: null
  val_percentage: 0.1
training_config:
  Decay: 0.0001
  LR: 0.01
  N_Epoch: 200
  backdoor: null
  bat_size: 64
  early_stopping: true
  monitor_name: mse
  patience: 20
  train_loss: mse_loss
  val_loss_criterias:
    mse: mse_loss
    rmse: rmse_loss
  validate_times: 20
  verbose: true
